# Site settings
title: Beware The Blog
email: njemanuel01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  njemanuel01

# Build settings
markdown: redcarpet
